name: scp_agreement
channels:
  - conda-forge
dependencies:
  - python=3.11
  - herbie-data
  - metpy
  - cartopy
  - cfgrib
  - eccodes
  - matplotlib
  - numpy
  - xarray
  - scipy
  - pandas
  - pip
  - pip:
    - ecmwf-opendata
